import Head from 'next/head'
import Image from 'next/image'
import path from 'path'
import { promises as fs } from 'fs'
import Header from '../components/Header'
import Footer from '../components/Footer'

export async function getStaticProps() {
  const jsonDirectory = path.join(process.cwd(), 'json')
  const fileContents = await fs.readFile(jsonDirectory + '/data.json', 'utf8')
  const conferences = JSON.parse(fileContents);

  return {
    props: {
      conferences,
    },
  }
}

export default function About({ conferences }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
      </main>
      <Footer />
    </>
  )
}
